[project]
name = "kn-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "graphviz>=0.20.3",
    "langchain-openai>=0.3.19",
    "langgraph>=0.4.8",
    "pytest>=8.4.0",
]
